#!/bin/bash
kerb="$HOME/kerberos"

docker_container=$(cat $kerb/run.sh | grep -E "^name="| cut -d"=" -f2)

get_status() {
    docker container ls --all --filter name=$docker_container --format '{{.ID}} {{.Image}} {{.State}} {{.Status}} {{.Names}} {{.Labels}}'
}
status=$(get_status)
date >> ~/running.log.txt
echo $status >> ~/running.log.txt

s=$(echo $status | awk '{print $3}')
if [[ "$s" = exited ]]; then
    echo Exit, restart
    docker container start $docker_container
    sleep 2
    ~/brightness.sh
    get_status
else
    echo good
fi
